### ISSUE TITLE
MudBlazor 7.7.0 not compatible

### ISSUE THREAD

**Issue by sikelio** [danheron/Heron.MudCalendar#167]
Good evening

I used MudCalendar in one of my Blazor Server project, and I found out that in some cases this last update causes an error.
I found out that it is because of the 7.7.0 update of MudBlazor. By retrograding to 7.6.0 it works normally

Heres the error I've got:

```
[20:31:38 WRN] Unhandled exception rendering component: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at MudBlazor.Utilities.CssBuilder.AddValue(String value)
   at MudBlazor.Utilities.CssBuilder.AddClass(String value)
   at MudBlazor.Utilities.CssBuilder.AddClass(String value, Boolean when)
   at Heron.MudCalendar.DayWeekViewBase.TimeCellClassname(Int32 row)
   at Heron.MudCalendar.DayWeekViewBase.<get_RenderTimes>b__45_0(RenderTreeBuilder __builder2)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at Heron.MudCalendar.DayWeekViewBase.<get_Render>b__40_0(RenderTreeBuilder __builder2)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at Heron.MudCalendar.DayWeekViewBase.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
[20:31:38 ERR] Unhandled exception in circuit 'LhTFpqjvLg9gEJNGY1quv2LzrLbyjf5hKQqFKTmExAI'.
System.NullReferenceException: Object reference not set to an instance of an object.
   at MudBlazor.Utilities.CssBuilder.AddValue(String value)
   at MudBlazor.Utilities.CssBuilder.AddClass(String value)
   at MudBlazor.Utilities.CssBuilder.AddClass(String value, Boolean when)
   at Heron.MudCalendar.DayWeekViewBase.TimeCellClassname(Int32 row)
   at Heron.MudCalendar.DayWeekViewBase.<get_RenderTimes>b__45_0(RenderTreeBuilder __builder2)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at Heron.MudCalendar.DayWeekViewBase.<get_Render>b__40_0(RenderTreeBuilder __builder2)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at Heron.MudCalendar.DayWeekViewBase.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
[20:31:38 ERR] Location change to 'http://localhost:5064/planning' in circuit 'LhTFpqjvLg9gEJNGY1quv2LzrLbyjf5hKQqFKTmExAI' failed.
Microsoft.AspNetCore.Components.LocationChangeException: An exception occurred while dispatching a location changed event.
 ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Threading.ReaderWriterLockSlim'.
   at System.Threading.ReaderWriterLockSlim.TryEnterReadLockCore(TimeoutTracker timeout)
   at System.Threading.ReaderWriterLockSlim.EnterReadLock()
   at MudBlazor.SnackbarService.get_ShownSnackbars()
   at MudBlazor.SnackbarService.NavigationManager_LocationChanged(Object sender, LocationChangedEventArgs e)
   at Microsoft.AspNetCore.Components.NavigationManager.NotifyLocationChanged(Boolean isInterceptedLink)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Components.NavigationManager.NotifyLocationChanged(Boolean isInterceptedLink)
   at Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost.<>c__DisplayClass51_0.<OnLocationChangedAsync>b__1()
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<InvokeAsync>g__Execute|8_0(ValueTuple`3 state)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost.OnLocationChangedAsync(String uri, String state, Boolean intercepted)
```

If you want to recreate this error heres some of my code  so you can try to figure out:

`TeacherPlanning.razor`
```razor
<MudGrid Class="mt-0">
    <MudItem xs="12" sm="12" Class="d-block d-md-none pt-0">
        <MudCalendar ShowMonth="false"
                     ShowWeek="false"
                     ShowCurrentTime="true"
                     ShowDay="true"
                     ShowTodayButton="true"
                     @bind-CurrentDay="_currentDay"
                     Items="_reservations"
                     DateRangeChanged="DateRangeChanged"
                     ShowDatePicker="false"
                     DayCellHeight="15"
                     ItemClicked="OnItemClicked">
            <CellTemplate>
                <div style="width: 100%; height: 100%; border: 2px solid @GetColor(((TeacherItem)context).Color); background-color: white">
                    <div style="background-color: @GetColor(((TeacherItem)context).Color)">
                        <MudText Style="color: #ffffff;"
                                 Typo="Typo.body1"
                                 Align="Align.Center">
                            @(((TeacherItem)context).Location)
                        </MudText>
                    </div>

                    <div class="px-2 pt-2"><MudText Typo="Typo.body2">@context.Text</MudText></div>
                    <div class="px-2"><MudText Typo="Typo.body2">@(((TeacherItem)context).Groups)</MudText></div>
                </div>
            </CellTemplate>
        </MudCalendar>
    </MudItem>

    <MudItem md="12" Class="d-none d-md-block pt-0">
        <MudCalendar ShowMonth="false"
                     ShowWeek="true"
                     ShowCurrentTime="true"
                     ShowDay="false"
                     ShowTodayButton="true"
                     @bind-CurrentDay="_currentDay"
                     Items="_reservations"
                     DateRangeChanged="DateRangeChanged"
                     ItemClicked="OnItemClicked">
            <CellTemplate>
                <div style="width: 100%; height: 100%; border: 2px solid @GetColor(((TeacherItem)context).Color); background-color: white">
                    <div style="background-color: @GetColor(((TeacherItem)context).Color)">
                        <MudText Style="color: #ffffff;"
                                 Typo="Typo.body1"
                                 Align="Align.Center">
                            @(((TeacherItem)context).Location)
                        </MudText>
                    </div>

                    <div class="px-2 pt-2"><MudText Typo="Typo.body2">@context.Text</MudText></div>
                    <div class="px-2"><MudText Typo="Typo.body2">@(((TeacherItem)context).Groups)</MudText></div>
                </div>
            </CellTemplate>
        </MudCalendar>
    </MudItem>
</MudGrid>
```

`TeacherPlanning.razor.cs`
```cs
using Project.Server.Services;
using Project.Shared.Models.Api.Teacher.GetTeacherPlanning;
using FrApp42.Web.API;
using Heron.MudCalendar;
using Microsoft.AspNetCore.Components;
using Microsoft.JSInterop;
using MudBlazor;
using Nextended.Core.Extensions;
using System.Security.Principal;

namespace Project.Components.Shared.Planning
{
    public partial class TeacherPlanning
    {
        [Inject]
        private ApiConfig Config { get; set; }

        [Inject]
        private Endpoints Endpoints { get; set; }

        [Inject]
        private IDialogService DialogService { get; set; }

        [Inject]
        private PdfService Pdf { get; set; }

        [Inject]
        private IJSRuntime JS { get; set; }

        [Inject]
        private ILogger<TeacherPlanning> Logger { get; set; }

        [Inject]
        private LogService LogService { get; set; }

        [Parameter]
        public IIdentity User { get; set; }

        private List<TeacherItem> _reservations = [];
        private DateTime _currentDay;
        private bool _includeColleague = false;

        protected override void OnInitialized()
        {
            _currentDay = DateTime.Today;
        }

        private async Task LoadPlanning(DateTime date)
        {
            DateTime startOfWeek = GetFirstDayOfWeek(date);
            DateTime endOfWeek = startOfWeek.AddDays(6);

            Request request = new(Endpoints.GetTeacherPlanning(User.Name), HttpMethod.Get);
            request
                .AddQueryParam("start", startOfWeek.ToString("yyyyMMdd"))
                .AddQueryParam("end", endOfWeek.ToString("yyyyMMdd"))
                .AddHeader("Authorization", Config.Key)
                .AcceptJson();

            Result<GetTeacherPlanning> result = await request.Run<GetTeacherPlanning>();

            _reservations = [];

            if (result.StatusCode == 200 && result.Value != null)
            {
                if (result.Value.Reservations == null)
                    return;

                foreach (Reservation reservation in result.Value.Reservations)
                {
                    _reservations.Add(new TeacherItem()
                    {
                        Text = reservation.Name,
                        Groups = string.Join(", ", reservation.Groups.Select(g => g.Name).ToArray()),
                        Start = DateTime.Parse(reservation.Start),
                        End = DateTime.Parse(reservation.End),
                        Location = reservation.Location,
                        Color = reservation.Type == "TEST" ? Color.Error : Color.Primary,
                        isCollegue = reservation.IsTeacherReservation
                    });
                }
            }
            else
            {
                LogService.Write(Logger, LogLevel.Error, $"GetTeacherConvention error: {result.Error}");
            }
        }
        private DateTime GetFirstDayOfWeek(DateTime day)
        {
            DayOfWeek firstDayOfWeek = DayOfWeek.Monday;
            int offset = day.DayOfWeek - firstDayOfWeek;

            if (offset < 0)
            {
                offset += 7;
            }

            return day.AddDays(-offset).Date;
        }

        private async Task DateRangeChanged(DateRange dateRange)
        {
            _currentDay = (DateTime)dateRange.Start;

            await LoadPlanning(_currentDay);
            FilterCalendar(_includeColleague);
        }

        private string GetColor(Color color) => $"var(--mud-palette-{color.ToDescriptionString()})";

        private void FilterCalendar(bool includeColleague)
        {
            if (includeColleague)
            {
                _reservations = _reservations.ToList();
            }
            else
            {
                _reservations = _reservations.Where(r => r.isCollegue).ToList();
            }

            StateHasChanged();
        }

        private async Task OnIncludeColleagueChanged(bool value)
        {
            _includeColleague = value;

            await LoadPlanning(_currentDay);
            FilterCalendar(_includeColleague);
        }

        private async Task OnItemClicked(CalendarItem calendarItem)
        {
            TeacherItem item = (TeacherItem)calendarItem;

            string start = FormatDateTime(item.Start);
            string end = item.End.HasValue ? FormatDateTime(item.End.Value) : FormatDateTime(item.Start.AddHours(1));
            string id = $"{DateTime.Now.ToUnixTimeStamp()}_{item.Text.Replace(' ', '_').Replace('-', '_')}";

            var icsContent = $@"BEGIN:VCALENDAR
VERSION:2.0
BEGIN:VEVENT
SUMMARY:{item.Text}
DTSTART:{start}
DTEND:{end}
DTSTAMP:{FormatDateTime(DateTime.UtcNow)}
UID:{id}
DESCRIPTION:Groupe(s): {string.Join(", ", item.Groups)}
LOCATION:{item.Location}
ORGANIZER:example@mail.com
END:VEVENT
END:VCALENDAR";

            byte[] byteArray = System.Text.Encoding.UTF8.GetBytes(icsContent);
            using MemoryStream stream = new(byteArray);

            DotNetStreamReference streamReference = new(stream: stream);

            await Pdf.DownloadFileFromStream(JS, streamReference, $"{id}.ics");
        }

        private string FormatDateTime(DateTime dt) => dt.ToString("yyyyMMddTHHmmssZ");
    }

    class TeacherItem : CalendarItem
    {
        public string Groups { get; set; } = string.Empty;
        public string Location { get; set; } = string.Empty;
        public Color Color { get; set; } = Color.Primary;
        public bool isCollegue { get; set; }
    }
}
```

**Comment by digitaldirk** [comment]
Getting this as well

**Comment by phamilton4321** [comment]
Get the same as well in a Interactive Auto project, after it changed to WASM.

```cs
[07:05:16 ERR] Unhandled exception in circuit 'uuxZlYau73OblqUnX2AJIA2IqmozhYNg89AciDEs-VQ'.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Threading.ReaderWriterLockSlim'.
   at System.Threading.ReaderWriterLockSlim.TryEnterWriteLockCore(TimeoutTracker timeout)
   at System.Threading.ReaderWriterLockSlim.EnterWriteLock()
   at MudBlazor.SnackbarService.AddCore(SnackbarMessage message, Severity severity, Action`1 configure)
   at MudBlazor.SnackbarService.AddCore[T](String text, Dictionary`2 componentParameters, Severity severity, Action`1 configure, String key)
   at MudBlazor.SnackbarService.Add(String message, Severity severity, Action`1 configure, String key)
   at #######.Home.AddEntry() in ##########\Home.razor:line 386
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at MudBlazor.MudBaseButton.OnClickHandler(MouseEventArgs ev)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

**Comment by miladecode** [comment]
got the same!!!

**Comment by sikelio** [comment]
thank you man

**Comment by TDroogers** [comment]
@danheron Check this discussion. https://github.com/MudBlazor/MudBlazor/pull/9635#issuecomment-2331341800
