### ISSUE TITLE
v3.0.0-beta.1 javascript error

### ISSUE THREAD

**Issue by digitaldirk** [danheron/Heron.MudCalendar#198]
I upgraded my project to .net 9.0, MudBlazor to 8.0.0-preview.5, and MudCalendar to v3.0.0-beta.1

When going to a page that has a MudCalendar (I have a basic one, and one with custom overrides) I get this error:
```
blazor.server.js:1 
[2024-12-11T18:04:44.129Z] Error: Microsoft.JSInterop.JSException: Could not find 'positionMonthItems' ('positionMonthItems' was undefined).
Error: Could not find 'positionMonthItems' ('positionMonthItems' was undefined).
    at https://localhost:1234/_framework/blazor.server.js:1:374
    at Array.forEach (<anonymous>)
    at l.findFunction (https://localhost:1234/_framework/blazor.server.js:1:342)
    at b (https://localhost:1234/_framework/blazor.server.js:1:5091)
    at https://localhost:1234/_framework/blazor.server.js:1:2884
    at new Promise (<anonymous>)
    at w.beginInvokeJSFromDotNet (https://localhost:1234/_framework/blazor.server.js:1:2857)
    at Gt._invokeClientMethod (https://localhost:1234/_framework/blazor.server.js:1:63461)
    at Gt._processIncomingData (https://localhost:1234/_framework/blazor.server.js:1:64250)
    at Gt.connection.onreceive (https://localhost:1234/_framework/blazor.server.js:1:54841)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
   at Heron.MudCalendar.Services.JsService.PositionMonthItems(ElementReference element, String moreText, Boolean fixedHeight)
   at Heron.MudCalendar.MonthView.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

Let me know if I can test anything for this new version, thank you

**Comment by digitaldirk** [comment]
Error went away after clearing browser cache
